---
title: "ListenbyCode"
author: "Andrea Seisler"
date: "1/9/2019"
output: github_document
---

###Terms of Use  

Welcome, and thank for your intertest in ListenByCode Cooperation (“LBC”, “we”, ”our”, or “us” ). These terms of use govern your access to and use of the entire contents of the website available at https://www.listenbycode.com (“Website”) (including the Services) owned and operated by ListenByCode Cooperation. Please read these terms of use carefully before using the Website. They are a legal agreement between you and LBC. Using any part of the Website indicates that you accept these terms of use. If you do not accept these terms of use, please do not use the Website, cease downloading the Website, or leave the Website.
 
 
1. The Website and the Services
1.1 LBC offers and maintains the Website to provide one or more of the following Services to you:
(a) automated transcription of audio files uploaded to our Website;
(b) a audio/file format that we support are .WAV, .MP3, .PCM, .M4A;
(c) an editor that allows users to correct the content of the result.
(d) API is supported. See Document page. 
1.2 Demo Services are free. Some are paid for. Each new user have one hour free time to use our full fuction which includes 1.1. 
1.3 LBC is new company. Many functions are still in Beta as we create and refine. Your feedback will help us make LBC more effective and more useful. If you have any questions, concerns, or comments regarding these terms of use or anything else related to us, please contact.
 
2. Fees and Payment
2.1 You shall pay the applicable fee to us as set out in price page
 
3. Promotions and Marketing Offers
3.1 LBC may offer promotional offers from time to time which may include promo codes or account credits, may be subject to expiration dates and may only be applicable to selected users of the Website. LBC reserves the right to remove credit from a user account or end a promotion without notice if at the sole discretion of LBC it believes a user is not acting in good faith in relation to the terms of the promotion.
 
 
4. Terms and Conditions
4.1. LBC reserves the rights to change these terms and conditions at any time by posting changes online. Your continued use of this site after changes are posted constitutes your acceptance of this agreement as modified.
4.2. You agree to use this site only for lawful purposes, and in a manner which does not infringe the rights, or restrict, or inhibit the use and enjoyment of the site by any third party.
4.3. This site and the information, names, images, pictures, logos regarding or relating to LBC are provided “as is” without any representation or endorsement made and without warranty of any kind whether express or implied. In no event will LBC be liable for any damages including, without limitation, indirect or consequential damages, or any damages whatsoever arising from the use or in connection with such use or loss of use of the site, whether in contract or in negligence.
4.4. LBC does not warrant that the functions contained in the material contained in this site will be uninterrupted or error free, that defects will be corrected, or that this site or the server that makes it available are free of viruses or bugs or represents the full functionality, accuracy and reliability of the materials.
4.5. Copyright restrictions:
Commercial use or publication of all or any item displayed is strictly prohibited without prior authorisation from LBC. Nothing contained herein shall be construed as conferring any license by LBC to use any item displayed.
4.6. LBC takes no responsibility for the content of external Internet sites. Other websites that we link to are owned and operated by third parties and LBC has no control over them. The fact that we include links to other websites does not mean that we approves of or endorses any other third party website or the content of that website. We accept no liability for any statements, information, products or services that are published on or are accessible through any websites owned or operated by third parties.
4.7. If there is any conflict between these terms and conditions and rules and/or specific terms of use appearing on this site relating to specific material then the latter shall prevail.
4.8. If these terms and conditions are not accepted in full, the use of this site must be terminated immediately.



### Privacy Policy  

This privacy policy covers ListenByCode Coopration (“LBC”, “we”, ”our”, or “us” ) and its website. It describes the information that we gather, how we use and disclose such information and the steps we take to protect such information. 

By visiting the Site, you accept the privacy practices described in this Policy. 
You can browse our website without disclosing any Personal Data to us and we will only collect and store information that you volunteer if you complete our enquiry form. 

The Personal Data that we will collect will include:
- Your name
- Contact telephone number
- Company name
- E-mail address 
We may use the Personal Data for our own marketing purposes, including market research and to keep you up to date with any offers or information regarding our business.

If you receive commercial emails from us or information regarding our business, you may unsubscribe at any time by following the instructions contained within the email so that you do not receive any further communications.

Information about you will not be shared or transferred to any other company without your express consent.
We will make sure each file you upload will be deleted rapidly after you get results. And your transcript results will be deleted in three days. 

Our website may contain links to third party websites operating their own terms and conditions and privacy policies. LBC is not responsible for the policies of any linked third party sites. 
We respect your privacy rights therefore if you wish to amend Personal Data we hold about you or request that we delete the Personal Data held then you may contact us and we will have any reference to you deleted.



