---
title: "RevSpeech-terms"
author: "Andrea Seisler"
date: "1/4/2019"
output: github_document
---

[RevSpeech](https://www.rev.ai/)  
- Terms of Use not available  
- RevSpeech Privacy Statement not available  
- The Customer Agreement is the only documentation of any terms/privacy statment.  

----
  
REV.AI  
CUSTOMER AGREEMENT  

This Customer Agreement (this “Agreement”) is between Rev.com, Inc., a Delaware corporation (“Rev”), and ___________________ (“Customer”) and is effective as of ___________________, 20__ (the “Effective Date”).

Background

Rev has developed and makes available a service that leverages its machine learning-based proprietary speech recognition technology for transcribing audio or video recordings (the “Rev.ai Service”).  Customer desires to use the Rev.ai Service to transcribe Customer Content (as defined below) in accordance with the terms and conditions of this Agreement.

1.	Definitions

1.1	The following terms, when used in this Agreement will have the following meanings:

“Affiliates” means an entity that directly or indirectly Controls, is Controlled by, or is under common Control with another entity, so long as such Control exists.  For the purposes of this definition, “Control” means beneficial ownership of 50% or more of the voting power or equity in an entity.

“Confidential Information” means any information or data disclosed by either party that is marked or otherwise designated as confidential or proprietary or that should otherwise be reasonably understood to be confidential in light of the nature of the information and the circumstances surrounding disclosure.  However, “Confidential Information” will not include any information which (a) is in the public domain through no fault of receiving party; (b) was properly known to receiving party, without restriction, prior to disclosure by the disclosing party; (c) was properly disclosed to receiving party, without restriction, by another person with the legal authority to do so; or (d) is independently developed by the receiving party without use of or reference to the disclosing party’s Confidential Information.

“Customer Content” means audio or video recordings uploaded by Customer through the use of the Rev.ai Service.

“Documentation” means the technical and user documentation manuals made available by Rev for the Rev.ai Service.

“Order Form” means an order form, quote or other similar document that sets forth the term thereof, and pricing and volume minimums, if applicable, for the Rev.ai Service, and that references this Agreement and is mutually executed by the parties.  Order Form #1 is attached hereto in Exhibit A.

2.	Rev.ai Service

2.1	Provision of Rev.ai Service.  Subject to the terms and conditions of this Agreement, Rev will make the Rev.ai Service available to Customer pursuant to this Agreement and the applicable Order Form, and hereby grants Customer a non-exclusive right to access and use the Rev.ai Service to obtain transcriptions of Customer Content uploaded by Customer.  For clarity, this Agreement governs Customer’s use of the Rev.ai Service, and not the products offered at www.rev.com. 

2.2	Data Security.  Rev will maintain a security program materially in accordance with industry standards that is designed to (i) ensure the security and integrity of Customer Content; (ii) protect against threats or hazards to the security or integrity of Customer Content; and (iii) prevent unauthorized access to Customer Content.  In furtherance of the foregoing, Rev will maintain the administrative, physical and technical safeguards to protect the security of Customer Content that are described in the applicable Documentation.  Rev’s security safeguards include measures for preventing access, use, modification or disclosure of Customer Content by Rev personnel except (a) to provide the Rev.ai Service and prevent or address service or technical problems, (b) as required by applicable law, or (c) as Customer expressly permits in writing or under this Agreement.  Rev will not materially diminish the protections provided in this Section during the term of this Agreement.

2.3	Customer Limitations.  The rights granted herein are subject to the following restrictions (the “Use Restrictions”).  Customer will not directly or indirectly:

(a)	reverse engineer, decompile, disassemble, modify, create derivative works of or otherwise create, attempt to create or derive, or permit or assist any third party to create or derive, the trade secrets underlying the Rev.ai Service;

(b)	attempt to probe, scan or test the vulnerability of the Rev.ai Service, breach the security or authentication measures of the Rev.ai Service without proper authorization or wilfully render any part of the Rev.ai Service unusable;

(c)	use or access the Rev.ai Service to develop a product or service that is competitive with Rev’s products or services or engage in competitive analysis or benchmarking;

(d)	transfer, distribute, resell, lease, license, or assign the Rev.ai Service or otherwise offer the Rev.ai Service on a standalone basis; or

(e)	otherwise use the Rev.ai Service outside the scope expressly permitted hereunder and in the applicable Order Form.

2.4	Customer Responsibilities.

(a)	Customer will (i) be responsible for all use of the Rev.ai Service under its account, (ii) use commercially reasonable efforts to prevent unauthorized access to or use of the Rev.ai Service and notify Rev promptly of any such unauthorized access or use and (iii) be responsible for obtaining and maintaining any equipment, software and ancillary services needed to connect to, access or otherwise use the Rev.ai Service, including as set forth in the Documentation.

(b)	Customer will not use the Rev.ai Service to transmit or provide to Rev any financial or medical information of any nature, or any sensitive personal data (e.g., social security numbers, driver’s license numbers, birth dates, personal bank account numbers, passport or visa numbers and credit card numbers).

2.5	Affiliates.  Any Affiliate of Customer will have the right to enter into an Order Form executed by such Affiliate and Rev and this Agreement will apply to each such Order Form as if such Affiliate were a signatory to this Agreement.  With respect to such Order Forms, such Affiliate becomes a party to this Agreement and references to Customer in this Agreement are deemed to be references to such Affiliate.  Each Order Form is a separate obligation of the Customer entity that executes such Order Form, and no other Customer entity has any liability or obligation under such Order Form.

3.	Fees

3.1	Fees. Customer will pay Rev fees for the Rev.ai Service based on the pricing set forth in the applicable Order Form.  Except as otherwise specified herein or in any applicable Order Form, (a) fees are quoted and payable in United States dollars and (b) payment obligations are non-cancelable, and fees paid are non-refundable.  All fees are due within 30 days after receipt of an invoice therefor. Rev may change such pricing upon [30] days prior written notice (email to suffice) to Customer.

3.2	Late Payment.  Rev may suspend access to the Rev.ai Service immediately upon notice if Customer fails to pay any amounts hereunder at least five (5) days past the applicable due date.  In addition, unpaid amounts are subject to a finance charge of 1.5% per month on any outstanding balance, or the maximum permitted by law, whichever is lower.

3.3	Taxes.  All amounts payable hereunder are exclusive of any sales, use and other taxes or duties, however designated (collectively “Taxes”).  Customer will be solely responsible for payment of all Taxes, except for those taxes based on the income of Rev.  Customer will not withhold any taxes from any amounts due to Rev.

4.	Proprietary Rights and Confidentiality

4.1	Proprietary Rights.  As between the parties, Rev exclusively owns all right, title and interest in and to the Rev.ai Service and Rev’s Confidential Information, and Customer exclusively owns all right, title and interest in and to the Customer Content and Customer’s Confidential Information.  To the extent Rev obtains any right, title or interest in or to the transcriptions the Rev.ai Service creates from the Customer Content, Rev hereby assigns all such right, title and interest to Customer.

4.2	Confidentiality.  Each party agrees that it will use the Confidential Information of the other party solely in accordance with the provisions of this Agreement and it will not disclose, or permit to be disclosed, the same directly or indirectly, to any third party without the other party’s prior written consent, except as otherwise permitted hereunder.  However, either party may disclose Confidential Information (a) to its employees, officers, directors, attorneys, auditors, financial advisors and other representatives who have a need to know and are legally bound to keep such information confidential by confidentiality obligations consistent with those of this Agreement; and (b) as required by law (in which case the receiving party will provide the disclosing party with prior written notification thereof, will provide the disclosing party with the opportunity to contest such disclosure, and will use its reasonable efforts to minimize such disclosure to the extent permitted by applicable law.  Neither party will disclose the terms of this Agreement to any third party, except that either party may confidentially disclose such terms to actual or potential lenders, investors or acquirers.  Each party agrees to exercise due care in protecting the Confidential Information from unauthorized use and disclosure.  In the event of actual or threatened breach of the provisions of this Section or the Use Restrictions, the non-breaching party will be entitled to seek immediate injunctive and other equitable relief, without waiving any other rights or remedies available to it.  Each party will promptly notify the other in writing if it becomes aware of any violations of the confidentiality obligations set forth in this Agreement.

4.3	Machine Learning.  Customer acknowledges that a fundamental component of the Rev.ai Service is the use of machine learning for the purpose of improving and providing Rev’s products and services.  Notwithstanding anything to the contrary, Customer agrees that Rev is hereby granted the right to use Customer Content submitted hereunder to train its algorithms internally through machine learning techniques for such purpose.

4.4	Service Improvements; Rev.ai Service Metrics.  Customer agrees that Rev has the right to collect, retain and use internally Customer Content and other information relating to the performance of the Rev.ai Service, during and after the term hereof, to (i) improve Rev’s products and services, and (ii) disclose statistics and metrics regarding the Rev.ai Service (e.g., number of files transcribed using the Rev.ai Service across all customers) solely in an aggregated and anonymized format that does not identify Customer or any individual.

5.	Warranties and Disclaimers

5.1	Rev.  Rev warrants that it will, consistent with prevailing industry standards, perform the Rev.ai Service in a professional and workmanlike manner and the Rev.ai Service will conform in all material respects with the Documentation.  For breach of the foregoing express warranty, Customer’s exclusive remedy shall be the re-performance of the deficient Rev.ai Service or, if Rev cannot re-perform such deficient Rev.ai Service as warranted, Customer will not be required to pay for such deficient Rev.ai Service.

5.2	Customer.  **_Customer warrants that it has all rights necessary to provide any information, data or other materials that it provides hereunder, and to permit Rev to use the same as contemplated hereunder._**

5.3	DISCLAIMERS.  EXCEPT AS EXPRESSLY SET FORTH HEREIN, EACH PARTY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE.  CUSTOMER ACKNOWLEDGES THAT THE REV.AI SERVICE IS BASED ON PREDICTIVE STATISTICAL MODELS, INTERPRETATIONS OF AUDIOVISUAL CONTENT AND DEPENDENT IN PART ON THE QUALITY OF CUSTOMER CONTENT THAT IS PROVIDED.  THE REV.AI SERVICE MAY CONTAIN BUGS, MAKE ERRORS OR MISINTERPRET CUSTOMER CONTENT.  REV DOES NOT REPRESENT OR WARRANT THAT HUMAN INTERVENTION WILL NOT BE REQUIRED OR THAT ALL TRANSCRIPTIONS WILL BE 100% ACCURATE.

5.4	BETA PRODUCTS.  FROM TIME TO TIME, CUSTOMER MAY HAVE THE OPTION TO PARTICIPATE IN A PROGRAM WITH REV WHERE CUSTOMER GETS TO USE ALPHA OR BETA PRODUCTS, FEATURES OR DOCUMENTATION (COLLECTIVELY, “BETA PRODUCTS”) OFFERED BY REV. THE BETA PRODUCTS ARE NOT GENERALLY AVAILABLE AND ARE PROVIDED “AS IS”.  REV DOES NOT PROVIDE ANY INDEMNITIES, SERVICE LEVEL COMMITMENTS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE, IN RELATION THERETO.  CUSTOMER OR REV MAY TERMINATE CUSTOMER’S ACCESS TO THE BETA PRODUCTS AT ANY TIME.

6.	Indemnification

6.1	Indemnity by Rev.  Rev will defend Customer against any claim, demand, suit, or proceeding (“Claim”) made or brought against Customer by a third party alleging that the use of the Rev.ai Service as permitted hereunder infringes or misappropriates a United States patent, copyright or trade secret and will indemnify Customer for any damages finally awarded against (or any settlement approved by Rev) Customer in connection with any such Claim; provided that (a) Customer will promptly notify Rev of such Claim, (b) Rev will have the sole and exclusive authority to defend and/or settle any such Claim (provided that Rev may not settle any Claim without Customer’s prior written consent, which will not be unreasonably withheld, unless it unconditionally releases Customer of all related liability) and (c) Customer reasonably cooperates with Rev in connection therewith.  If the use of the Rev.ai Service by Customer has become, or in Rev’s opinion is likely to become, the subject of any claim of infringement, Rev may at its option and expense (i) procure for Customer the right to continue using and receiving the Rev.ai Service as set forth hereunder; (ii) replace or modify the Rev.ai Service to make it non-infringing (with comparable functionality); or (iii) if the options in clauses (i) or (ii) are not reasonably practicable, terminate this Agreement.  Rev will have no liability or obligation with respect to any Claim if such Claim is caused in whole or in part by (A) compliance with designs, guidelines, plans or specifications provided by Customer; (B) use of the Rev.ai Service by Customer not in accordance with this Agreement; (C) Customer Content or (D) the combination, operation or use of the Rev.ai Service with other applications, portions of applications, product(s) or services where the Rev.ai Service would not by itself be infringing.  This Section states Rev’s sole and exclusive liability and obligation, and Customer’s exclusive remedy, for any claim of any nature related to infringement or misappropriation of intellectual property.

6.2	Indemnification by Customer.  Customer will defend Rev against any Claim made or brought against Rev by a third party arising out of the Customer Content, and Customer will indemnify Rev for any damages finally awarded against (or any approved settlement) Rev in connection with any such Claim; provided that (a) Rev will promptly notify Customer of such Claim, (b) Customer will have the sole and exclusive authority to defend and/or settle any such Claim (provided that Customer may not settle any Claim without Rev’s prior written consent, which will not be unreasonably withheld, unless it unconditionally releases Rev of all liability) and (c) Rev reasonably cooperates with Customer in connection therewith.

7.	Limitation of Liability

EXCEPT FOR A PARTY’S INDEMNIFICATION OBLIGATIONS, OR A BREACH OF CONFIDENTIALITY OR THE USE RESTRICTIONS, UNDER NO LEGAL THEORY, WHETHER IN TORT, CONTRACT, OR OTHERWISE, WILL EITHER PARTY BE LIABLE TO THE OTHER FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES OF ANY CHARACTER, INCLUDING DAMAGES FOR LOSS OF GOODWILL, LOST PROFITS, LOST SALES OR BUSINESS, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, LOST CONTENT OR DATA, OR FOR ANY AND ALL OTHER DAMAGES OR LOSSES, EVEN IF A REPRESENTATIVE OF SUCH PARTY HAS BEEN ADVISED, KNEW OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES, OR (B) EXCLUDING CUSTOMER’S PAYMENT OBLIGATIONS, ANY DIRECT DAMAGES, COSTS, OR LIABILITIES IN EXCESS OF THE AMOUNTS PAID BY CUSTOMER HEREUNDER DURING THE TWELVE (12) MONTHS PRECEDING THE INCIDENT OR CLAIM.

8.	Termination

8.1	Term.  The term of this Agreement will commence on the Effective Date and continue until terminated as set forth below. The initial term of each Order Form will begin on the Order Form Effective Date of such Order Form and will continue for the subscription term set forth therein.  Except as set forth in such Order Form, the term of such Order Form will automatically renew for successive renewal terms equal to the length of the initial term of such Order Form, unless either party provides the other party with written notice of non-renewal at least thirty (30) days prior to the end of the then-current term.

8.2	Termination.  Each party may terminate this Agreement or an Order Form upon five (5) days prior written notice to the other party.  

8.3	Survival.  Upon termination of this Agreement all rights and obligations will immediately terminate except that any terms or conditions that by their nature should survive such termination will survive, including the Use Restrictions and terms and conditions relating to proprietary rights and confidentiality, disclaimers, indemnification, limitations of liability and termination and the general provisions below.

9.	General

9.1	Insurance.  Rev shall, during the term of this Agreement, maintain in force the following insurance coverage at its own cost and expense: (a) Statutory Worker’s Compensation and Employer’s Liability as required by state law with a minimum limit of $1,000,000 each accident / $1,000,000 each disease / $1,000,000 policy limit per occurrence, Disability and Unemployment Insurance, and all other insurance as required by law, including Employer’s Liability Insurance with limits of no less than $1,000,000 per occurrence, or any amount required by applicable law, whichever is greater; (b) Commercial General Liability, on an occurrence basis, including premises-operations, product completed-operations, broad form property damage, contractual liability, independent contractors and personal liability, with a minimum combined single limit of $1,000,000 per occurrence, naming Customer as an additional insureds; and (c) Professional Errors and Omissions coverage covering the Rev.ai Service, with coverage limits of not less than $1,000,000 per claim or per occurrence/$1,000,000 aggregate, placed either on an “occurrence” basis or on a “claims made” basis; (d) Umbrella Liability with $6,000,000 per occurrence; (e) D&O, EPL & Crime liability insurance with $1,000,000 each.

9.2	Export Compliance.  Each party will comply with the export laws and regulations of the United States, European Union and other applicable jurisdictions in providing and using the Rev.ai Service.

9.3	Publicity.  Customer agrees that Rev may refer to Customer’s name and trademarks in Rev’s marketing materials and website; however, Rev will not use Customer’s name or trademarks in any other publicity (e.g., press releases, customer references and case studies) without Customer’s prior written consent (which may be by email).

9.4	Assignment; Delegation.  Neither party hereto may assign or otherwise transfer this Agreement, in whole or in part, without the other party’s prior written consent, except that either party may assign this Agreement without consent to a successor to all or substantially all of its assets or business related to this Agreement.  Any attempted assignment, delegation, or transfer by either party in violation hereof will be null and void.  Subject to the foregoing, this Agreement will be binding on the parties and their successors and assigns.

9.5	Amendment; Waiver.  No amendment or modification to this Agreement, nor any waiver of any rights hereunder, will be effective unless assented to in writing by both parties.  Any such waiver will be only to the specific provision and under the specific circumstances for which it was given, and will not apply with respect to any repeated or continued violation of the same provision or any other provision.  Failure or delay by either party to enforce any provision of this Agreement will not be deemed a waiver of future enforcement of that or any other provision.

9.6	Relationship.  Nothing contained herein will in any way constitute any association, partnership, agency, employment or joint venture between the parties hereto, or be construed to evidence the intention of the parties to establish any such relationship. Neither party will have the authority to obligate or bind the other in any manner, and nothing herein contained will give rise or is intended to give rise to any rights of any kind to any third parties.

9.7	Unenforceability.  If a court of competent jurisdiction determines that any provision of this Agreement is invalid, illegal, or otherwise unenforceable, such provision will be enforced as nearly as possible in accordance with the stated intention of the parties, while the remainder of this Agreement will remain in full force and effect and bind the parties according to its terms.

9.8	Governing Law.  This Agreement will be governed by the laws of the State of California, exclusive of its rules governing choice of law and conflict of laws.  This Agreement will not be governed by the United Nations Convention on Contracts for the International Sale of Goods.

9.9	Notices.  Any notice required or permitted to be given hereunder will be given in writing by personal delivery, certified mail, return receipt requested, or by overnight delivery.  Notices to the parties must be sent to the respective address set forth in the signature blocks below.

9.10	Entire Agreement.  This Agreement comprises the entire agreement between Customer and Rev with respect to its subject matter, and supersedes all prior and contemporaneous proposals, statements, sales materials or presentations and agreements (oral and written).  No oral or written information or advice given by Rev, its agents or employees will create a warranty or in any way increase the scope of the warranties in this Agreement.

9.11	Force Majeure.  Neither Party will be deemed in breach hereunder for any cessation, interruption or delay in the performance of its obligations due to causes beyond its reasonable control (“Force Majeure Event”), including earthquake, flood, or other natural disaster, act of God, labor controversy, civil disturbance, terrorism, war (whether or not officially declared), cyber attacks (e.g., denial of service attacks), or the inability to obtain sufficient supplies, transportation, or other essential commodity or service required in the conduct of its business, or any change in or the adoption of any law, regulation, judgment or decree.

9.12	Government Terms.  Rev provides the Rev.ai Service, including related software and technology, for ultimate federal government end use solely in accordance with the terms of this Agreement.  If Customer (or any of its customers) is an agency, department, or other entity of any government, the use, duplication, reproduction, release, modification, disclosure, or transfer of the Rev.ai Service, or any related documentation of any kind, including technical data, software, and manuals, is restricted by the terms of this Agreement.  All other use is prohibited and no rights than those provided in this Agreement are conferred. The Rev.ai Service was developed fully at private expense.

9.13	Interpretation.  For purposes hereof, “including” means “including without limitation”.

[Remainder of Page Intentionally Left Blank]

 
IN WITNESS WHEREOF, the duly authorized representatives of each of the parties hereto have executed this Agreement as of the date of the last signature hereof.
Customer:
By:  	
Name:  
Title:  	Rev:
By:  	
Name:  
Title:  
Address for notice	Address for notice
Rev.com, Inc.
222 Kearny St., 8th Floor
San Francisco, California 94108
Attn: Legal


 
Exhibit A
Order Form #1

