---
title: "Wit"
author: "Andrea Seisler"
date: "1/10/2019"
output: github_document
---

### Terms

Wit.ai Terms of Service
Last Modified: May 24th, 2018

Wit.AI, Inc. ("Wit", "we", "our", or "us") provides an online software platform that enables developers to build and deploy natural language interfaces for devices and software applications (the "Wit Platform").

These API Terms of Service (these "Terms" or the "Agreement") include the legal terms that we require all developers to accept and implement as a condition of accessing our website located at https://wit.ai (the "Website") and/or accessing or using the application programming interfaces provided on or in connection with the Wit Platform ("API(s)"), including any documentation, materials, code, data (such as Expressions, Intents, and Entities, each as defined below), and other information or materials made available to you by Wit on or in connection with the APIs (collectively, "Wit Content") to develop natural language interfaces for use in connection with your products or devices ("Devices") and/or your software applications ("Application(s)").

The Wit Platform includes a project repository designed to allow you to access, input, and store data in connection with your language interface development project ("Wit App(s)"). Data contained in each Wit App may include "Expressions", "Intents", and "Entities". An "Expression" is an actual utterance or phrase spoken by an individual; an "Intent" is the command or desired action that the speaker of the Expression would like the Device or Application to perform; and an "Entity" is a value or subset of data associated with the Intent. For more information on Expressions, Intents, and Entities, please see the online documentation.

PLEASE READ THESE TERMS CAREFULLY TO ENSURE THAT YOU UNDERSTAND EACH PROVISION. THESE TERMS CONTAIN A MANDATORY INDIVIDUAL ARBITRATION AND CLASS ACTION/JURY TRIAL WAIVER PROVISION THAT REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIALS OR CLASS ACTIONS. Wit reserves the right to make unilateral modifications to these terms and will provide notice of these changes as described below.

BY USING OR CONTINUING TO USE THE WIT APIS OR BY CLICKING "Go down the rabbit hole" YOU AGREE TO USE THE WIT APIS AND OTHER WIT CONTENT SOLELY IN ACCORDANCE WITH THE TERMS AND CONDITIONS OF THESE API TERMS OF SERVICE, AND YOU AGREE THAT YOU ARE BOUND BY AND ARE A PARTY TO THESE TERMS. YOU WARRANT THAT YOU ARE NOT A CONSUMER YOU ARE AT LEAST EIGHTEEN (18) YEARS OLD AND THAT YOU HAVE THE LEGAL CAPACITY TO AGREE TO AND BE BOUND BY THESE TERMS. IF YOU ACCESS OR USE THE WIT APIS, OTHER WIT CONTENT, OR WIT PLATFORM ON BEHALF OF A COMPANY, PRINCIPAL OR OTHER ENTITY, YOU REPRESENT THAT YOU HAVE AUTHORITY TO BIND SUCH ENTITY AND ITS AFFILIATES TO THESE TERMS AND THAT THESE TERMS ARE FULLY BINDING UPON THEM. IN SUCH CASE, THE TERM "YOU" WILL REFER TO YOU AND SUCH ENTITY AND ITS AFFILIATES. IF YOU DO NOT HAVE AUTHORITY, OR IF YOU DO NOT AGREE WITH THE TERMS AND CONDITIONS OF THESE API TERMS OF SERVICE, YOU MAY NOT ACCESS OR USE THE APIS OR OTHER WIT CONTENT.


Accounts and Registration
Accounts
i. You need to use a current Wit account or create a new Wit account in order to use the APIs and other Wit Content.

ii. You may use the Wit Content and/or Wit Platform only if you can form a binding contract with Wit, and only in compliance with these Terms and all applicable local, state, national, and international laws, rules and regulations.

iii. Any use or access to the Website, APIs, or Wit Platform by anyone under 18 is strictly prohibited and in violation of these Terms.

iv. You must be a human. Accounts registered by "bots" or other automated methods are not permitted.

v. You are solely responsible for the activity that occurs on your account (including, without limitation, any Customer Data and Profile Content (each as defined below) provided under or through your account.

vi. You may create a Wit account using your GitHub account credentials or via other registration methods we may provide from time to time, in our sole discretion. By connecting to the Wit Platform with a third-party service, you give us permission to access and use your information from that service as permitted by that service, and to store your log-in credentials for that service. It's your responsibility to keep your password, account credentials, and accounts secure. You must notify Wit immediately if any unauthorized use, or suspected unauthorized use, of your Wit account occurs or if any other breach of security occurs.

vii. You may never use another user's account without permission. Your login may only be used by one person. A single login shared by multiple individuals is not permitted.

viii. You acknowledge that Wit is not liable for any loss or damage arising from your failure to comply with the above requirements.

Registration
i. You are required to provide certain information (e.g., your contact details, description of your product or service, your targeted number of users, etc.) as part of the registration process to access the Wit Content, or as part of your continued use of the Wit Content.

ii. You agree that any registration information you give to Wit will always be accurate and up to date, and you agree to promptly notify Wit of any changes in your account information.

Use of Wit Content
Right to Access and Use of Wit Content.
Subject to the terms and conditions of these Terms, Wit grants you a limited, revocable, non-transferable, non-exclusive, right (without the right to sublicense) to access and use the Wit Content and Wit Platform, solely to the extent necessary for you to create a natural language interface that operates solely in connection with your Devices and/or Applications.

Permitted Access.
You will access (or attempt to access) an API or other Wit Content only as expressly permitted by these Terms and the means described in the documentation or instructions Wit provides.

API Calls.
Wit may set limits on the number of API calls that you can make at its sole discretion, for example in the interest of service stability. If you exceed these limits, Wit may throttle your activity or cease offering you access to the APIs altogether in Wit's sole discretion. You agree to such limitations and will not attempt to circumvent such limitations.

Open Source Software.
Some of the software required by or included in the Wit Content may be offered under an open source license. There may be provisions in the open source license that expressly override some of these Terms, and in those cases, the overriding provisions apply.

Accuracy.
We do not guarantee the accuracy of any Wit Content, including any output generated in connection with your use of the Wit Content or Wit Platform. You acknowledge and agree that you use and rely on the Wit Content and the Wit Platform at your own risk, and that Wit will not be liable for any errors or inaccuracies of any Wit Content or the Wit Platform.

Monitoring.
Wit may, but is under no obligation to, monitor the use of the Wit Content to ensure quality, improve Wit products and services, or verify your compliance with these Terms. You will not interfere with such monitoring.

Compliance with Law.
You will use our APIs and other Wit Content and the Wit Platform only as permitted by law (including without limitation laws regarding the import or export of data or software, privacy, or local laws). You will not use the APIs or other Wit Content to encourage or promote illegal or dangerous activity. You also will require any end users of your Devices or Applications ("End Users") to comply with any applicable law and these Terms. You will not knowingly enable your End Users to violate applicable law or these Terms.

Prohibitions
When using any Wit Content and/or the Wit Platform, unless otherwise approved in writing by Wit, the following prohibitions apply:

You will not use the APIs or other Wit Content on behalf of any third party, unless such third party has expressly authorized you to access and use the Wit Content under its account.
You will not copy, rent, lease, sell, transfer, assign, sublicense, dissemble, reverse engineer or decompile (except to the limited extent expressly authorized by applicable statutory law), modify or alter any part of the Website, APIs, other Wit Content, or the Wit Platform.
You will not create an Application that functions substantially the same as the APIs or other Wit Content and offer it for use by third parties.
You will not use the Wit Content or Wit Platform in connection with any Device or Application that is targeted to children under the age of thirteen (13).
You will not perform an action with the intent of introducing to the Website, Wit Content, or Wit Platform or the applications or products of any third party, any viruses, worms, defects, Trojan horses, malware or any items of a destructive nature.
You will not use the Wit Content or Wit Platform, or access or control any customer accounts, products, devices, or applications in a manner that could cause harm, damage, or loss to any individual, or otherwise harm, defame, abuse, harass, stalk or threaten others or allow or encourage any third party to do so.
You will not use the APIs, other Wit Content, or the Wit Platform in any manner or for any purpose that may violate any law or regulation, or any right of any person including, but not limited to, intellectual property rights, rights of privacy and/or rights of personality, or which otherwise may be harmful (in Wit's sole discretion) to Wit, its service providers, its suppliers, end users of the Wit Platform, End Users, or any individual or entity.
You will not use the APIs, other Wit Content, or the Wit Platform in connection with any inherently dangerous objects, devices, materials, or situations, or in furtherance of any activities likely to cause harm to any individual or property.
You will not: (i) interfere with or disrupt the Website, Wit Platform, the APIs, or the servers or networks providing the APIs; (ii) tamper with the security of the any of the hardware, software or networks used by Wit to make the Website, Wit Content, or Wit Platform available or tamper with any customer accounts; (iii) disable, circumvent or avoid any security device, mechanism, protocol or procedure established by Wit; or (iv) permit others to do any of the foregoing.
Compliance
Wit reserves the right to investigate any Device or Application for compliance with these Terms. Such investigations may include Wit accessing and using your Device or Application, for example to identify stability or security issues that could affect Wit or its customers. You consent to any such investigation. Wit may immediately suspend or terminate access to the Website, APIs, other Wit Content, and the Wit Platform by you or your Device or Application without notice if we believe, in our sole discretion, that you are in violation of these Terms or otherwise.

Privacy and Security
Customer Data.
"Customer Data" means any and all information you provide to or through the Website, Wit Content, or the Wit Platform, including, but not limited to, Expressions, Intents, and Entities entered by you, voice and utterance data, Profile Content (as defined below), and data that relates to any End Users or such End Users' use of your Device or Application ("End User Data"). You acknowledge and agree that you are solely responsible for obtaining all required consents from End Users in connection with any use of your Devices or Applications and the Wit Content (including the APIs), which consent shall be compliant with all applicable data protection legislation and other privacy laws, rules, and regulations. Before collecting any End User Data or other information from End Users, you must provide adequate notice of what End User Data and other information you collect and how it will be used and/or shared and obtain any necessary consents. You and your Devices and Applications will comply with all privacy laws and regulations in connection with your access and use of the Wit Content and Wit Platform. You will provide and adhere to a privacy policy for your Device or Application that: (i) complies with all applicable laws, rules, and regulations, (ii) is conspicuously displayed to all End Users, and (iii) clearly and accurately describes to End Users what data and user information you collect (such as personally identifiable information, login information, etc.) and how you use and share such information with Wit and third parties. You understand that by using the Wit Content or Wit Platform, you consent to the collection, use, and disclosure of any Customer Data (including personal information and Aggregate and De-Identified Data) in accordance with these Terms, and to have Customer Data collected, used, transferred to and processed in the United States. You shall be solely responsible for your Customer Data and the consequences of making it available on or through the Wit Content and/or Wit Platform.

Privacy.
You understand that by using the Wit Content and/or Wit Platform you consent to the collection, use and disclosure of your personally identifiable information and Customer Data as set forth in our Privacy Policy and these Terms, and to have your personally identifiable information and Customer Data collected, used, transferred to and processed in the United States.

The Data Processing Addendum will apply to the extent that personal data of EU data subjects is contained in the Customer Data and provided by you to Wit for processing. If there is any conflict between the main part of these Terms of Service and the Data Processing Addendum, the Data Processing Addendum prevails.

Security.
Wit cares about the integrity and security of your Customer Data and personal information. However, we cannot guarantee that unauthorized third parties will never be able to defeat our security measures or use your personal information for improper purposes. You acknowledge that you are solely responsible for any personal injury or property damage arising from or relating to your use of any Wit Content, the Wit Platform, or any authorized or unauthorized use of your Device or Application.

Wit Profiles
When you register for a Wit account, we will automatically create a public profile page on the Wit Platform under your username ("Wit Profile"), and you expressly authorize us to create a Wit Profile on your behalf. You acknowledge and agree that any Customer Data that is available to the public, as provided in these Terms (and in accordance with the Wit Privacy Policy), will be populated into your Wit Profile. We may allow you to upload content, information, and links to your Wit Profile (collectively, "Profile Content"). Wit takes no responsibility and assumes no liability for any Profile Content that you or any other Wit user or third party posts or otherwise makes available on or through the Wit Content or Wit Platform. You shall be solely responsible for your Profile Content and the consequences of making it available through the Wit Platform.

DMCA
Since we respect content owner rights, it is Wit's policy to respond to alleged infringement notices that comply with the Digital Millennium Copyright Act of 1998 ("DMCA"), as provided in our DMCA Policy. .

Ownership and License
Your Devices, Applications, and Customer Data.
Wit does not acquire ownership of your Devices, Applications, or Customer Data by your use of the APIs or other Wit Content. You represent and warrant that you have the necessary rights to provide all Customer Data, including without limitation, End User Data and Profile Content, and other information you make available in connection with your use of the Wit Content and/or the Wit Platform and to grant all rights and licenses under these Terms. Without limiting the foregoing, if you are using the Wit Content or Wit Platform on behalf of your employer or any third party, you represent and warrant that your employer or such third party has expressly authorized you to make available and use any content, data, or information that you use or make available in connection with your use of the Wit Content and/or Wit Platform. You further represent and warrant that your Customer Data (including, without limitation, End User Data and Profile Content), Applications, and/or Devices, and any use thereof in connection with the Wit Content or Wit Platform will not violate the rights of any third party, including but not limited to, intellectual property rights, trade secret rights or other proprietary rights, or rights of privacy, or violate any applicable laws, rules, or regulations.

Customer Data Rights and License.
i. General. In connection with the operation of the Wit Content and Wit Platform, Wit receives, utilizes, and analyzes Customer Data. You retain ownership of your Customer Data. However, notwithstanding anything to the contrary (and whether you select the Open App or Private App), you hereby grant Wit a license to: (i) use and disclose your Customer Data to provide the Wit Content and the Wit Platform; (ii) use your Customer Data for Wit's internal business purposes; (iii) disclose your Customer Data as may be required by law or legal process; and (iv) otherwise use and disclose your Customer Data in accordance with the Wit Privacy Policy. We may also use the information that we collect to operate, maintain and improve the systems and infrastructure that provide the Wit Content and Wit Platform. You authorize us to do so and acknowledge that this may also result in improvements to our services and those of our affiliates, as centralized systems and infrastructure support the Wit Platform, Wit Content, and our affiliates' services. For example, we may use crash logs from your use of Wit Platform and Wit Content to identify and fix bugs that may also be present in the affiliates' services. Without limiting the foregoing and regardless of your Wit App type (Open or Private), you agree that Wit is expressly and irrevocably authorized to utilize, analyze, modify, reproduce, publish, share, create derivative works of, or otherwise exercise all rights in your Customer Data and any analytics, statistics or other data related to or derived from your Customer Data and/or your use of the Wit Content or Wit Platform for any purpose, provided that such data is in aggregate or de-identified form ("Aggregate and De-Identified Data"). Subject to the Customer Data licenses, you acknowledge and agree that Wit will exclusively own all right, title, and interest in and to all Aggregate and De-Identified Data and other output data generated by the Wit Platform. Notwithstanding anything to the contrary, if you ever have any ownership interest in any Aggregate and De-Identified Data or output data, you hereby assign to Wit all such right, title, and interest in and to such Aggregate and De-Identified Data and output data, including all intellectual property rights therein. You also hereby grant each user of the Wit Content and/or Wit Platform a non-exclusive license to access your Customer Data in accordance with your account settings through the Wit Content and/or Wit Platform, and to use, reproduce, distribute, display and perform such Customer Data as permitted through the functionality of the Wit Content and/or Wit Platform and under these Terms.

ii. Open App. If you choose to use the Wit Content and/or Wit Platform under an Open Wit App, you acknowledge and agree that any Expressions, Intents, or Entities you provide in connection with your use of the Wit Content or Wit Platform will be available to all other users of the Wit Content and Wit Platform. You expressly authorize the use of such data by other Wit users as permitted by the functionality of the Wit Content and/or Wit Platform.

iii. Private App. Subject to the rights granted above, if you choose to use the Wit Content and/or Wit Platform under a Private app, other users of the Wit Content and/or Wit Platform will not be able to directly use or access your Expressions, Intents, or Entities, unless you choose to make such data public in connection with your Wit Profile, or as otherwise provided in these Terms.

Wit Content and Wit Platform.
By using our Website, APIs, other Wit Content, or Wit Platform, you do not acquire ownership of any rights in our Website, APIs, other Wit Content, the Wit Platform, or any data, content or information that is transmitted or accessed through our APIs, including without limitation, any Expressions, Intents, Entities, or other data provided by Wit or other Wit users. Except for your Customer Data, as between you and Wit, the Wit Content, the Wit Platform, and all data, content, and information that is contained in or transmitted or accessed through our APIs and/or the Wit Platform, including, without limitation, software, Expressions, Intents, Entities, machine learning models, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music, and data belonging to other users, and all intellectual property rights related thereto, are the exclusive property of Wit and its licensors.

Feedback.
If we receive any feedback, suggestions, ideas, reports, or other information relating to any Wit Content or any Wit products or services, we may use such information without obligation to you.

Restrictions; Retained Rights.
The Website, Wit Content, and Wit Platform are protected by United States intellectual property laws, including without limitation copyright laws, and international treaty provisions. You will not remove or alter any proprietary notices or marks on any Wit Content or the Wit Platform. You will not reverse engineer or attempt to extract the source code from any API, other Wit Content, the Wit Platform, or any related software, except to the extent that this restriction is expressly prohibited by applicable law. You also will not sublicense, lease, rent, loan, distribute, sell, transfer or make available the APIs or other Wit Content or the Wit Platform to any third party except as specifically permitted by these Terms. Wit Content is licensed and not sold. Wit reserves all rights not expressly granted in these Terms.

Updates to APIs
We reserve the right to modify or update the Website, Wit Content and/or Wit Platform at any time, for any reason, and without notice to you. If Wit makes updates, revisions, breaking changes or in any way modifies an API or other Wit Content, you agree that you are solely responsible for making changes to your Device or Application to ensure continued service for your End Users. We are constantly changing and improving our APIs and other Wit Content. We may add or remove functionalities or features at our discretion, for any reason, and we do not guarantee that your Device or Application will function with any future or modified versions of any Wit Content or the Wit Platform.

Branding and Attribution
Wit Brand
. Except where expressly stated, these Terms do not grant either party any right, title or interest in or to the other party's trade names, trademarks, service marks, logos, domain names, and other distinctive brand features (collectively, "Marks").

Attribution.
You agree to display any attribution(s) required by Wit as described in any documentation for the APIs or other Wit Content. Without limiting the foregoing, users of the Community Plan must display "Powered by Wit" and a link to wit.ai on any Device or Application connected to the APIs. Wit grants to you a limited, freely revocable, nontransferable, nonsublicenseable, nonexclusive license during the term of your subscription to display Wit's Marks solely for the purpose of promoting or advertising that your use the APIs and other Wit Content. You must only use the Wit Marks in accordance with these Terms. You understand and agree that Wit has the sole discretion to determine whether your attribution(s) and use of Wit's Marks is in accordance with the above requirements and any applicable guidelines.

Publicity.
You will not make any statement regarding your use of an API that suggests partnership with, sponsorship by or endorsement by Wit without Wit's prior written approval.

Promotional and Marketing Use.
In the course of promoting, marketing, or demonstrating the APIs you are using, Wit may produce and distribute incidental depictions, including screenshots, video, or other content from your Application or Device, and may use your company or product name and logos. You hereby grant Wit all necessary rights for these purposes.

Termination
Termination.
You may change your App type or stop using our APIs and other Wit Content at any time. If you want to change your Private App to an Open App, you must log into your Wit App and make your App open. If you want to terminate your account and these Terms, you must email us at contact@wit.ai and inform us of your intention to cancel your account ("Termination Notice"). At that point, you can request to get a copy of your data (Expressions, Intents, and Entities). Subject to the post-termination obligations and the surviving provisions set forth in these Terms, upon our written acknowledgement of our receipt of your Termination Notice, these Terms will terminate. Wit has the right to immediately terminate these Terms or discontinue your use of the Website, Wit Platform, the APIs and other Wit Content or any portion or feature thereof for any reason and at any time without liability or other obligation to you. Upon any termination or expiration of these Terms or discontinuation of your access to any Wit Content, you must immediately cease all use of the Wit Platform, any Wit Content (including the APIs), and Wit Marks and delete all copies thereof.

Surviving Provisions.
When these Terms come to an end, those terms that by their nature are intended to continue indefinitely will continue to apply, including but not limited to: Sections 3 - 9, 10A, 10C, 10D, 11B, and 12 - 15.

No Warranties
THE WIT CONTENT AND WIT PLATFORM ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. USE OF THE WIT CONTENT AND WIT PLATFORM IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE WIT CONTENT AND WIT PLATFORM ARE PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM WITH OR THROUGH THE WIT CONTENT OR WIT PLATFORM WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. WITHOUT LIMITING THE FOREGOING, WIT, ITS SUBSIDIARIES, ITS AFFILIATES, AND ITS LICENSORS DO NOT WARRANT THAT THE WIT CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE WIT CONTENT OR WIT PLATFORM WILL MEET YOUR REQUIREMENTS; THAT THE WIT CONTENT OR WIT PLATFORM WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE WIT CONTENT OR WIT PLATFORM IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WIT CONTENT OR WIT PLATFORM IS DOWNLOADED AND USED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD OR YOUR USE OF THE WIT CONTENT OR WIT PLATFORM.

FEDERAL LAW, SOME STATES, PROVINCES AND OTHER JURISDICTIONS DO NOT ALLOW EXCLUSIONS AND LIMITATIONS OF CERTAIN IMPLIED WARRANTIES, SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.

LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL WIT, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, THAT RESULT FROM THE USE OF, OR INABILITY TO USE, THE WIT CONTENT OR WIT PLATFORM. UNDER NO CIRCUMSTANCES WILL WIT BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE WIT CONTENT OR WIT PLATFORM OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN.

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WIT ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF THE WIT CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF THE WIT CONTENT OR WIT PLATFORM; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE WIT CONTENT OR WIT PLATFORM; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH THE WIT CONTENT OR WIT PLATFORM BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY WIT CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY WIT CONTENT OR OTHER CONTENT OR DATA TRANSMITTED OR OTHERWISE MADE AVAILABLE THROUGH THE WIT PLATFORM; AND/OR (VII) CUSTOMER DATA OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY. IN NO EVENT SHALL WIT, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS, OR LICENSORS BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES OR COSTS IN AN AMOUNT EXCEEDING THE AMOUNT YOU PAID TO WIT HEREUNDER IN THE TWELVE (12) MONTHS PRIOR TO THE DATE THE LAST CAUSE OF ACTION AROSE OR $10.00, WHICHEVER IS GREATER.

THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, BREACH OF STATUTORY DUTY, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF WIT HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.

SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS OF LIABILITY UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.

If any provision or part-provision of this section is or becomes invalid, illegal or unenforceable, it shall be deemed modified to the minimum extent necessary to make it valid, legal and enforceable. If such modification is not possible, the relevant provision or part-provision shall be deemed deleted. Any modification or deletion under this section shall not affect the validity and enforceability of the rest of these Terms.

You acknowledge that the Wit Content and Wit Platform may allow you to control Devices, Applications, and other third-party objects, which may affect the safety of End Users, other individuals, and property. You acknowledge that your use of the Wit Content and/or Wit Platform could lead to injury of individuals or damage or destruction of property. In using the Wit Content and Wit Platform, you must design and test your Devices and Applications to ensure that your Devices and Applications do not present risks of personal injury or death, property damage, or other losses. You must implement all reasonable security measures to ensure that no third party may gain unauthorized access to the Wit Platform or Wit Content. If you choose to use the Wit Content or Wit Platform in any way, you assume all risk that your use of the Wit Content or Wit Platform causes any damage, harm, injury, or loss, including without limitation to any End Users or other individuals or property. You agree that you are solely responsible for any damage, harm, injury, or loss arising from or relating to your Device or Application or your use of any Wit Content or the Wit Platform, and you agree to hold us harmless from all such damage, harm, injury, or loss.

Indemnification
You agree to defend, indemnify and hold harmless Wit and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Wit Content (including the APIs) or Wit Platform, including any data or content transmitted or received by you; (ii) your violation or alleged violation of any term of these Terms, including without limitation your breach of any of the representations and warranties above; (iii) any violation of any third-party right, including without limitation any right of privacy or intellectual property rights, by you, your Customer Data, Device, or Application, or any use thereof; (iv) your violation of any applicable law, rule or regulation; (v) any of your Customer Data or any that is transmitted via your account; (vi) any personal injury or property damage arising from or relating to your use of the Wit Content or Wit Platform or any authorized or unauthorized use of your Device or Application; or (vii) any other party's access and use of the Wit Content or Wit Platform with your unique username, password or other appropriate security code.

Other Legal Terms and Conditions
Independent Development.
These Terms do not impair Wit's right to develop, manufacture, purchase, use or market, directly or indirectly, alone or with others, products or services competitive with those offered by you.

Confidential Information.
Our communications to you may contain Wit confidential information. If you receive any materials or communications that are clearly confidential or marked confidential, then you will not disclose the Wit confidential information to any third party without Wit's prior written consent.

Notifications and Modification.
Wit may provide notifications, whether such notifications are required by law or are for marketing or other business related purposes, to you via email notice, written or hard copy notice, or through posting of such notice on our website, as determined by Wit in our sole discretion and subject to complying with applicable laws. Wit reserves the right to determine the form and means of providing notifications to our users. Wit is not responsible for any automatic filtering you or your network provider may apply to email notifications we send to the email address you provide us. Wit may, in its sole discretion, modify or update these Terms from time to time, and so you should review this page periodically. When we change these Terms in a material manner, we will update the 'last modified' date at the top of this page. Your continued use of the Wit Content or Wit Platform after any such change constitutes your acceptance of the new Terms of Service. If you do not agree to any of these Terms or any future Terms of Service, do not use or access (or continue to access) the Wit Content or Wit Platform.

Governing Law.
These Terms shall be governed by the internal substantive laws of the State of California, without respect to its conflict of laws principles. The parties acknowledge that these Terms evidence a transaction involving interstate commerce. Notwithstanding the preceding sentences with respect to the substantive law, any arbitration conducted pursuant to the terms and conditions of these Terms shall be governed by the Federal Arbitration Act (9 U.S.C. §§ 1-16). The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. You agree to submit to the personal jurisdiction of the federal and state courts located in Santa Clara County, California for any actions for which we retain the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of our copyrights, trademarks, trade secrets, patents, or other intellectual property or proprietary rights, as set forth in the Arbitration provision below, including any provisional relief required to prevent irreparable harm. You agree that Santa Clara County, California is the proper forum for any appeals of an arbitration award or for trial court proceedings in the event that the arbitration provision below is found to be unenforceable.

Arbitration.
READ THIS SECTION CAREFULLY BECAUSE IT REQUIRES THE PARTIES TO ARBITRATE THEIR DISPUTES AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM WIT. For any dispute with Wit, you agree to first contact us at contact@wit.ai and attempt to resolve the dispute with us informally. In the unlikely event that Wit has not been able to resolve a dispute it has with you after sixty (60) days, we each agree to resolve any claim, dispute, or controversy (excluding any claims for injunctive or other equitable relief as provided below) arising out of or in connection with or relating to these Terms, or the breach or alleged breach thereof (collectively, "Claims"), by binding arbitration by JAMS, Inc. ("JAMS"), under the Optional Expedited Arbitration Procedures then in effect for JAMS, except as provided herein. JAMS may be contacted at www.jamsadr.com. The arbitration will be conducted in Santa Clara County, California, unless you and Wit agree otherwise. If you are using the Wit Content or Wit Platform for commercial purposes, each party will be responsible for paying any JAMS filing, administrative and arbitrator fees in accordance with JAMS rules, and the award rendered by the arbitrator shall include costs of arbitration, reasonable attorneys' fees and reasonable costs for expert and other witnesses. If you are an individual using the Wit Content or Wit Platform for non-commercial purposes: (i) JAMS may require you to pay a fee for the initiation of your case, unless you apply for and successfully obtain a fee waiver from JAMS; (ii) the award rendered by the arbitrator may include your costs of arbitration, your reasonable attorney's fees, and your reasonable costs for expert and other witnesses; and (iii) you may sue in a small claims court of competent jurisdiction without first engaging in arbitration, but this does not absolve you of your commitment to engage in the informal dispute resolution process. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Nothing in this Section shall be deemed as preventing Wit from seeking injunctive or other equitable relief from the courts as necessary to prevent the actual or threatened infringement, misappropriation, or violation of our data security, intellectual property rights or other proprietary rights.

Class Action/Jury Trial Waiver.
WITH RESPECT TO ALL PERSONS AND ENTITIES, REGARDLESS OF WHETHER THEY HAVE OBTAINED OR USED THE WIT CONTENT OR WIT PLATFORM FOR PERSONAL, COMMERCIAL OR OTHER PURPOSES, ALL CLAIMS MUST BE BROUGHT IN THE PARTIES' INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION OR OTHER REPRESENTATIVE PROCEEDING. THIS WAIVER APPLIES TO CLASS ARBITRATION, AND, UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS. YOU AGREE THAT, BY ENTERING INTO THIS AGREEMENT, YOU AND WIT ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING OF ANY KIND.

General Legal Terms.
These Terms control the relationship between Wit and you. They do not create any third party beneficiary rights. If the Wit Content or Wit Platform is licensed to the United States government or any agency thereof, then the Wit Content and Wit Platform will be deemed to be "commercial computer software" and "commercial computer software documentation," respectively, pursuant to DFARS Section 227.7202 and FAR Section 12.212, as applicable. Any use, reproduction, release, performance, display or disclosure of the Wit Content or Wit Platform and any accompanying documentation by the U.S. Government will be governed solely by the terms and conditions of these Terms and is prohibited except to the extent expressly permitted by the terms and conditions of these Terms. The Wit Content and Wit Platform originate in the United States, and are subject to United States export laws and regulations. The Wit Content and Wit Platform may not be exported or re-exported to certain countries or those persons or entities prohibited from receiving exports from the United States. In addition, the Wit Content and Wit Platform may be subject to the import and export laws of other countries. You agree to comply with all United States and foreign laws related to use of the Wit Content and the Wit Platform. No waiver of any term of these Terms shall constitute a further or continuing waiver of such term or any other term, and Wit's failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. These Terms and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Wit without restriction. Any attempted transfer or assignment in violation hereof shall be null and void. These Terms, together with the Addendum, any amendments and any additional agreements you may enter into with Wit in connection with the Wit Content or Wit Platform, shall constitute the entire agreement between you and Wit concerning the Wit Content and Wit Platform. If any provision of these Terms is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms, which shall remain in full force and effect, except that in the event of unenforceability of the universal Class Action/Jury Trial Waiver, the entire arbitration agreement shall be unenforceable.

Contact.
Please contact us at contact@wit.ai with any questions regarding these Terms.

Data Processing Addendum

This Data Processing Addendum will apply to the extent that personal data of EU data subjects is contained in the Customer Data and provided by you to Wit for Processing.

Definitions
Within this Data Processing Addendum, "GDPR" means the General Data Protection Regulation (Regulation (EU) 2016/679), and "Controller", "Data Processor", "Data Subject", "Personal Data", "Personal Data Breach" and "Processing" shall have the same meanings as are defined in the GDPR. "Processed" and "Process" shall be construed in accordance with the definition of "Processing". All other defined terms herein shall have the same meanings as are defined elsewhere in the Terms.

Data Processing
In conducting its activities as Processor under this Agreement in relation to any Personal Data within the Customer Data ("Your Personal Data"), Wit confirms that:
the duration, subject matter, nature and purpose of the Processing shall be as specified in the Agreement;
the types of Personal Data Processed shall include any Personal Data within the End User Data;
the categories of Data Subjects include your representatives, End Users and any other individuals identified or identifiable by Your Personal Data; and
your obligations and rights as Data Controller in relation to Your Personal Data are as set out in this Agreement.
To the extent that Wit Processes Your Personal Data under or in connection with the Agreement, Wit shall:
only Process Your Personal Data in accordance with your instructions as set out under the Terms, including your instructions in these Terms in respect of the transfer of Your Personal Data, subject to any exceptions permitted by Article 28(3)(a) of the GDPR;
ensure that those of its employees authorised to Process Your Personal Data under this Agreement have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality in relation to Your Personal Data;
implement appropriate technical and organisational measures to protect personal data;
respect the conditions referred to below in Sections 2(iii) and 2(iv) of this Data Processing Addendum when appointing sub-Processors;
assist you by appropriate technical and organisational measures, insofar as this is possible through the Wit Content and Wit Platform, to enable you to fulfil your obligations to respond to requests for the exercise of rights by a Data Subject under Chapter III of the GDPR;
assist you in ensuring compliance with your obligations pursuant to Articles 32 to 36 GDPR taking into account the nature of the Processing and the information which is available to Wit;
on termination of the Agreement, delete Your Personal Data pursuant to the Agreement, unless European Union or Member State law requires Personal Data to be retained;
make available to you the information described in this Agreement and via the Wit Platform in satisfaction of Wit's obligation to make available all information that is necessary to demonstrate compliance with the obligations of Wit under Article 28 GDPR; and
on an annual basis, procure that a third party auditor of Wit's choice conducts a SOC 2 Type II or other industry standard audit as may be deemed appropriate by Wit of Wit's controls relating to the Wit Platform, such third party auditor being hereby mandated by you. At your request, Wit will provide you with a copy of its then-current audit report and such report will be deemed Wit's confidential information.
You authorise Wit to subcontract its data Processing obligations under this Agreement to Wit's affiliates, and to other third parties, a list of which Wit will provide to you upon your written request. Wit shall do so only by way of a written agreement with such sub-Processor which imposes the same data protection obligations on the sub-Processor as are imposed on Wit under this Agreement. Where that sub-Processor fails to fulfil such obligations, Wit shall remain fully liable to you for the performance of that sub-Processor's data protection obligations.
Where Wit engages an additional or replacement sub-Processor(s), Wit shall inform you of such additional or replacement sub-Processor(s) no later than fourteen (14) days in advance of the appointment of such additional or replacement sub-Processor(s). You may object to the engagement of such additional or replacement sub-Processor(s) within fourteen (14) days of being so informed by Wit by terminating the Agreement immediately on written notice to Wit.
Wit shall notify you without undue delay upon becoming aware of a Personal Data Breach relating to Your Personal Data. Such notice shall include, at the time of notification or as soon as possible after notification, relevant details of the Personal Data Breach where possible, including the number of your records affected, the category and approximate number of affected Users, anticipated consequences of the breach and any actual or proposed remedies, where appropriate, for mitigating the possible adverse effects of the breach.


### Privacy Policy  

Wit.ai Privacy Policy
Welcome to Wit.ai, Inc. ("we"or "Wit"), the provider of the software platform that enables developers to build and deploy natural language interfaces for devices and software applications (the "Wit Platform"). Wit is committed to protecting the privacy of all those who access or use our Service ("you," or "Users"). This Privacy Policy ("Policy") applies to our website, located at https://wit.ai, and the Wit Platform (collectively, our "Service"). Terms not defined in this Privacy Policy are defined in our Terms of Service.

INFORMATION WE COLLECT
Through the course of providing our Service through the Wit Platform, developers (who are our customers) may provide us with information from or about their End Users, or their End Users' use of their Device or Application (including personal information), including, but not limited to, utterance data, Expressions, Intents and Entities ("Customer Data"). In all of these cases, our software has been integrated into developers' products or applications and, to the extent that we process Customer Data, we do so on the behalf of developers for the purpose of providing the Service to them and in accordance with the Terms of Service. For clarity, the processing of Customer Data (in respect of which Wit acts as a Data Processor, not a Data Controller) is not governed by this Policy. Please check with the relevant developer about the policies it has in place to protect the personal data of its End Users.

We also process the following personal information from our developer users (collectively referred to as "Wit Data") in order to provide our Services. Wit.ai Inc. is the controller of Wit Data. The categories of information we collect can include:

Information you provide to the Wit website. We may collect and store personal information you provide to our Service when you register for an account or provide it to us in some other manner, including your name, email address, phone number, user name and password, when you register for our Service, request a demo or contact us for information about our Service. When you register for our Service, we will create a Wit Profile for you, containing information such as your screenname and URLs, which are displayed publicly. Where we provide forums, blogs or bulletins that allow for user-generated content, we may also collect and store personal information that you provide in relation to such content in accordance with this Policy. We may also collect any communications between you and Wit, as well as any information you provide if you take part in any interactive features of the Service.

Information you permit us to receive from social networking sites. When you interact with our Service through various social media, such as when you login through GitHub, or interact with us on Facebook or Twitter, we may receive information from the social network site including your profile information, profile picture, gender, user name, user ID associated with your social media account, age range, language, country, friends list, and any other information you permit the social network to share with third parties. The data we receive is dependent upon your privacy settings with the social network. You should always review, and if necessary, adjust your privacy settings on third-party websites and services before linking or connecting them to our website or Service.

The provision of certain personal data is mandatory and may be required in accordance with a contractual requirement or to enter into a contract. The collection of any such data will be made clear at the time of collection of the information. If you choose not to submit this information, this may result in us not being able to provide the Service to you.

Use of cookies and other technology to collect information.

We automatically collect certain types of usage information when you visit our website or use our Service. When you visit the website, we may send one or more cookies - a small text file containing a string of alphanumeric characters - to your computer that uniquely identifies your browser and lets us help you log in faster and enhance your navigation through the site. A cookie may also convey information to us about how you use the Service (e.g., the pages you view, the links you click, how frequently you access the Service, and other actions you take on the Service), and allow us to track your usage of the Service over time. We may collect log file information from your browser or mobile device each time you access the Service. Log file information may include information such as your web request, Internet Protocol ("IP") address, browser type, information about your mobile device, referring / exit pages and URLs, number of clicks and how you interact with links on the Service, domain names, landing pages, pages viewed, and other such information. We may employ clear gifs (also known as web beacons) which are used to track the online usage patterns of our Users. In addition, we may also use clear gifs in HTML-based emails sent to our Users to track which emails are opened and which links are clicked by recipients. The information allows for more accurate reporting and improvement of the Service. We may also collect analytics data, or use third-party analytics tools, to help us measure traffic and usage trends for the Service. These tools collect information sent by your browser or mobile device, including the pages you visit, your use of third party applications, and other information that assists us in analyzing and improving the Service.

When you access our Service by or through a mobile device, we may receive or collect and store a unique identification numbers associated with your device ("Device ID"), mobile carrier, device type and manufacturer, phone number, and, depending on your mobile device settings, your geographical location data, including GPS coordinates (e.g. latitude and/or longitude) or similar information regarding the location of your mobile device.

We use or may use the data collected through cookies, log file, device identifiers, location data and clear gifs information to: (a) remember information so that you will not have to re-enter it during your visit or the next time you visit the site; (b) provide custom, personalized content and information, including advertising; (c) provide and monitor the effectiveness of our Service; (d) monitor aggregate metrics such as total number of visitors, traffic, usage, and demographic patterns on our website and our Service; (e) diagnose or fix technology problems; and (f) otherwise to plan for and enhance our service.

Please refer to your browser's or mobile device's technical information for instructions on how to delete and disable cookies, and other tracking/recording tools. (To learn more about cookies, clear gifs/web beacons and related technologies, you may wish to visit http://www.allaboutcookies.org and/or the Network Advertising Initiative's online resources, at http://www.networkadvertising.org). Depending on your mobile device, you may not be able to control tracking technologies through settings.

HOW WE USE THIS INFORMATION

Wit uses Customer Data to operate, maintain, provide and improve the Service, and to process requests from developers in accordance with our Terms of Service or as required by law.

Wit relies on a number of legal bases to lawfully process Wit Data for the purposes described below. We need to process Wit Data as necessary in order to provide our Services, in accordance with our Terms of Service. When we process data that you provide to us as necessary for performing our Terms of Service, you have the right to port it under the GDPR. We may also process Wit Data where necessary to further our legitimate interests and those of others, where those legitimate interests are not overridden by your rights or interests. Users based in the European Economic Area have the right to object to this processing based on legitimate interests and should contact us to do so. More specifically, we use Wit Data for the following purposes:

To provide, update, maintain and protect our Service. We use Wit Data to operate, maintain, and provide to you the features and functionality of the Service. This includes providing custom, personalized content and information such as diagnosing or fixing security or technical issues, analyzing and monitoring usage, trends and other activities that might disrupt our Service.

To communicate with you. We use Wit Data to communicate directly with you and to offer products and services to you and it is in our legitimate interest to promote our Services and issue our direct marketing. We may also send you Service-related emails or messages (e.g., account verification, changes or updates to features of the Service, technical and security notices). For more information about your communication preferences, see "Your Choices Regarding Your Information" below.

Safety and security. We may also use your information for safety and security purposes, including the sharing of your information for such purposes. We do so as it is necessary to deliver safe and secure Services in accordance with our Terms of Service.

As required by applicable law, legal process or regulation. We may process your personal information if applicable law, legal process or regulation requires us to do so.

SHARING WITH THIRD PARTIES

We may share your personal information in the instances described below in accordance with this Policy. For further information on your choices regarding your information, see the "Your Choices Regarding Your Information" section below.

Corporate affiliates. We may share your personal information with other companies owned by or under common ownership as Wit (such as the Facebook Family of Companies). We share infrastructure, systems and technology and they may use the information we share with them to help operate, provide, improve, understand, customize, support, and market our services and their offerings. This includes helping improve infrastructure and delivery systems, understanding how our Services or theirs are used, securing systems, and fighting spam, abuse, or infringement activities.

Third party vendors, consultants, business partners and other service providers. We engage third party companies or individuals to perform services on our behalf or in order to carry out their work for us, which may include content or service fulfillment, customer support, billing, or providing analytics services.

Third parties at your request. For example, information contained in your Wit Profile, including your GitHub ID, may be viewable to others on the Wit Platform, subject to your settings, and you may have the option to link your information on our Service with your friends via email or social media.

Business re-organization. If we sell all or part of our business, make a sale or transfer of assets or shares, or partake in a reorganization, financing, change of control or acquisition of all or a portion of our business by another company or third party or in the event of bankruptcy or related or similar proceedings, we may disclose and transfer your personal information to one or more third parties as part of that transaction.

Legal and safety reasons. We may process your personal information in order to (i) comply with any applicable law, regulation, subpoena/court order, legal process or other government request, (ii) enforce our Terms of Service, including the investigation of potential violations thereof, (iii) investigate and defend ourselves against any third party claims or allegations, (iv) protect against harm to the rights, property or safety of Wit, Users or the public as required or permitted by law, and (v) detect, prevent or otherwise address criminal, security or technical issues.

Aggregated information. We may also share information with others in an aggregated and depersonalized form that is no longer associated with and can no longer be linked to an identified or identifiable user or individual.

YOUR CHOICES REGARDING YOUR INFORMATION

You have choices regarding what and how your personal information is shared and used:

Marketing communications. If you do not wish to receive promotional emails, you can click the "unsubscribe" button on promotional email communications. Note that you are not permitted to unsubscribe or opt-out of non-promotional messages regarding your account, such as account verification, changes or updates to features of the Service, or technical and security notices.

YOUR RIGHTS: FOR EU USERS ONLY

Customer Data If your personal data is comprised in Customer Data, then you should contact the developer in relation to any statutory rights you may have to access, port, rectify, erase, restrict or object to developer's processing of your data.

Wit Data If your personal data is comprised in Wit Data and you are based in the European Economic Area, then you have rights to access and port this information, along with rights to rectify, erase, restrict and object to Wit processing your personal data including as set out above in "How We Use This Information". Please use the contact details set out below to contact us should you wish to exercise these rights. Without prejudice to any other rights you may have, if you are based in the EU you also have the right to file a complaint against Wit with your local supervisory authority.

DATA RETENTION

We will retain your information for as long as your account is active or as needed to provide you the Services. We will retain your personal data comprised in Wit Data for as long as is necessary for the purposes set out in this Notice or as needed for us to provide the Service or to perform our contract with you. We will retain and use your personal data to the extent necessary to comply with our legal obligations, to resolve disputes and to enforce our agreements.

DATA TRANSFERS

We are a global service and information collected through the Service may be stored and processed in the United States or any other country in which Wit or its subsidiaries, affiliates or service providers maintain facilities. If you are located in the European Economic Area or other regions with laws governing data collection and use that may differ from U.S. law, please note that we may transfer information, including personal information, to a country and jurisdiction that does not have the same data protection laws as your jurisdiction. These data transfers are necessary to provide the Service.

SECURITY AND STORAGE OF INFORMATION

Wit cares about the security of your information and uses appropriate organizational and technological safeguards to preserve the integrity and security of all information we collect and that we share with our service providers. However, no security system is impenetrable and we cannot guarantee the security of our systems.

PERSONS UNDER THE AGE OF 13

Wit does not knowingly collect or solicit any information from anyone under the age of 13 or knowingly allow such persons to register for the Service. The Service and its content are not directed at children under the age of 13. In the event that we learn that we have collected personal information from a child under age 13, we will delete that information as quickly as possible. If you believe that we might have any information collected from a child under 13, please contact us at contact@wit.ai.

LINKS TO THIRD PARTY WEBSITES

The Service may contain links to and from third party websites such as our business partners, advertisers, and social media sites. If you follow a link to any of these websites, please note that these websites have their own privacy policies and that we do not accept any responsibility or liability for their policies. Please check the individual policies before you submit any information to those websites.

UPDATES TO THIS POLICY

We may modify this Policy from time to time to reflect changes in our privacy practices. If we make any material changes to this Policy, we will notify you by contacting you through our services or by posting a notice on our website - or by some combination of these methods. In circumstances where you have not provided us with your contact information, we encourage you to periodically review the Website for the latest information on our privacy practices.

CONTACTING US

If you have questions about this Policy, or if you would like to exercise your statutory rights with respect to your personal information, please contact us at contact@wit.ai .

LAST REVISION DATE

This Policy was last revised on, and effective as of May 24th, 2018.